server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/face?serverTimezone=GMT%2B8
    username: root
    password: 123456
    platform: mysql
    # mysql 8.0.+使用的驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # mapper映射文件地址，这里我在src/main/resouces下新建文件夹mapper
  mapper-locations: classpath*:mapper/*.xml
  # 配置bean扫描目录，也可用注解
  type-aliases-package: classpath*:com.example.face.entity
